-- NOIR storefront backend: schema, constraints, indexes, RLS.
-- Design: the browser only ever gets read access to the catalogue (products, shipping methods).
-- Coupons, orders and order items have NO public policies; they are reached only through the
-- SECURITY DEFINER functions in the next migration (noir_functions), which validate input and compute every
-- price server-side.

create schema if not exists private;
revoke all on schema private from public, anon, authenticated;

create or replace function private.touch_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- ---------------------------------------------------------------- catalogue
create table public.products (
  id          bigint generated by default as identity primary key,
  name        text not null check (char_length(btrim(name)) between 2 and 120),
  price       integer not null check (price > 0),
  old_price   integer check (old_price is null or old_price >= price),
  category    text not null check (category = lower(category) and char_length(category) between 2 and 40),
  image       text not null,
  sale        boolean not null default false,
  popular     boolean not null default false,
  is_active   boolean not null default true,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
comment on table public.products is 'Storefront catalogue. Prices are whole rupees (INR).';

create index products_active_id_idx on public.products (id) where is_active;
create index products_category_idx  on public.products (category) where is_active;

create trigger products_touch_updated_at
  before update on public.products
  for each row execute function private.touch_updated_at();

create table public.shipping_methods (
  id          text primary key check (id ~ '^[a-z_]+$'),
  label       text not null,
  eta         text not null,
  min_days    integer not null check (min_days >= 0),
  max_days    integer not null check (max_days >= min_days),
  fee         integer not null check (fee >= 0),
  free_from   integer check (free_from is null or free_from > 0),
  sort_order  integer not null default 0,
  is_active   boolean not null default true
);
comment on column public.shipping_methods.free_from is 'Order subtotal (before discount) from which this method is free. NULL = never free.';

create table public.coupons (
  code            text primary key check (code ~ '^[A-Z0-9_-]{3,32}$'),
  discount_type   text not null check (discount_type in ('percent', 'fixed')),
  discount_value  integer not null check (discount_value > 0),
  min_subtotal    integer not null default 0 check (min_subtotal >= 0),
  max_uses        integer check (max_uses is null or max_uses > 0),
  used_count      integer not null default 0 check (used_count >= 0),
  starts_at       timestamptz,
  expires_at      timestamptz,
  is_active       boolean not null default true,
  created_at      timestamptz not null default now(),
  constraint coupons_percent_range check (discount_type <> 'percent' or discount_value <= 100),
  constraint coupons_window check (starts_at is null or expires_at is null or expires_at > starts_at)
);

-- ---------------------------------------------------------------- orders
create table public.orders (
  id                  uuid primary key default gen_random_uuid(),
  order_number        text not null unique,
  idempotency_key     uuid unique,
  status              text not null default 'pending'
                        check (status in ('pending', 'confirmed', 'processing', 'shipped', 'delivered', 'cancelled')),
  payment_method      text not null check (payment_method in ('upi', 'card', 'netbanking', 'wallet')),
  payment_status      text not null default 'pending'
                        check (payment_status in ('pending', 'paid', 'failed', 'refunded')),
  shipping_method_id  text not null references public.shipping_methods (id),
  coupon_code         text,
  subtotal            integer not null check (subtotal >= 0),
  discount            integer not null default 0 check (discount >= 0),
  shipping            integer not null default 0 check (shipping >= 0),
  total               integer not null check (total >= 0),
  customer_name       text not null,
  customer_email      text not null,
  customer_phone      text not null check (customer_phone ~ '^[6-9][0-9]{9}$'),
  marketing_opt_in    boolean not null default false,
  ship_address        text not null,
  ship_city           text not null,
  ship_state          text not null,
  ship_pin            text not null check (ship_pin ~ '^[1-9][0-9]{5}$'),
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);
comment on table public.orders is 'Customer orders. Written only by public.create_order(); read via the Supabase dashboard / service role.';

create index orders_created_at_idx      on public.orders (created_at desc);
create index orders_customer_email_idx  on public.orders (lower(customer_email));
create index orders_status_idx          on public.orders (status);
create index orders_shipping_method_idx on public.orders (shipping_method_id);

create trigger orders_touch_updated_at
  before update on public.orders
  for each row execute function private.touch_updated_at();

create table public.order_items (
  id            bigint generated always as identity primary key,
  order_id      uuid not null references public.orders (id) on delete cascade,
  product_id    bigint not null references public.products (id),
  product_name  text not null,
  unit_price    integer not null check (unit_price > 0),
  quantity      integer not null check (quantity between 1 and 20),
  size          text not null check (size in ('S', 'M', 'L', 'XL'))
);
comment on column public.order_items.product_name is 'Snapshot at purchase time, so later catalogue edits do not rewrite history.';

create index order_items_order_idx   on public.order_items (order_id);
create index order_items_product_idx on public.order_items (product_id);

-- ---------------------------------------------------------------- abuse protection
create table private.rate_limits (
  key           text not null,
  bucket_start  timestamptz not null,
  hits          integer not null default 0,
  primary key (key, bucket_start)
);

-- ---------------------------------------------------------------- row level security
alter table public.products         enable row level security;
alter table public.shipping_methods enable row level security;
alter table public.coupons          enable row level security;
alter table public.orders           enable row level security;
alter table public.order_items      enable row level security;
alter table private.rate_limits     enable row level security;

create policy "Anyone can read active products"
  on public.products for select
  to anon, authenticated
  using (is_active);

create policy "Anyone can read active shipping methods"
  on public.shipping_methods for select
  to anon, authenticated
  using (is_active);

-- Least privilege: nothing is writable from the browser, and only the catalogue is readable.
revoke all on public.products, public.shipping_methods, public.coupons, public.orders, public.order_items
  from anon, authenticated;
grant select on public.products, public.shipping_methods to anon, authenticated;
